# Trending YouTube Videos Dataset - Foundations of Computer Science Project

## Files without encoding issues

In [1]:
#In this cell we are reading the datasets that do not have any encoding issues
#We import the pandas library in order to exploit the pandas function: pd.read_csv('filepath')
import pandas as pd

#We initially added an 'r' before the file paths so that python ignores blacklash
CAvideos = pd.read_csv(r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_csv_files\CAvideos.csv") 
DEvideos = pd.read_csv(r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_csv_files\DEvideos.csv")
FRvideos = pd.read_csv(r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_csv_files\FRvideos.csv")
GBvideos = pd.read_csv(r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_csv_files\GBvideos.csv")
INvideos = pd.read_csv(r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_csv_files\INvideos.csv")
USvideos = pd.read_csv(r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_csv_files\USvideos.csv")
#I used a separate variables to store the results of the pd.read_csv function for each CSV file

## Files with encoding issues

In [2]:
#In this cell we are reading the datasets with encoding issues
JPvideos = pd.read_csv(r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_csv_files\JPvideos.csv", encoding="latin-1")
KRvideos = pd.read_csv(r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_csv_files\KRvideos.csv", encoding="latin-1")
MXvideos = pd.read_csv(r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_csv_files\MXvideos.csv", encoding="latin-1")
RUvideos = pd.read_csv(r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_csv_files\RUvideos.csv", encoding="latin-1")

#we applied the encoding latin-1 so that we can use a function developed by Chatgpt to fix the encoding problem
#----------------------------------------------------------------------------------------------------


# Function to fix "mojibake" (like â€™, Ã±, or Â£)
def fix_mojibake(corrupted_string):
    """Fixes strings that were UTF-8 but read as Latin-1."""
    if pd.isna(corrupted_string) or not isinstance(corrupted_string, str): 
        return corrupted_string #If this value is missing OR if it is anything other than a string, leave it alone and just return it as-is, it's like a guard..
    try:
        return corrupted_string.encode('latin-1').decode('utf-8')
        # Step 1: Convert the "wrongg" string back into raw bytes using Latin-1.
        # Step 2: Re-interpret those same bytes as UTF-8 to get the correct characters.
    except Exception:
        #If anything goes wrong during this conversion just stop trying and give us the original data back.
        return corrupted_string
        
#--------------------------------------------------------------------------------------------------------------------        

# Generic function to apply the fix to a DataFrame
def fix_encoding_dataframe(df, text_columns=['title', 'channel_title', 'tags', 'description']):
    """
    Applies the mojibake fix to the specified text columns in a DataFrame.
    """
    for col in text_columns:
        if col in df.columns:
            df[col] = df[col].apply(fix_mojibake)
        else:
            print(f"Warning: Column '{col}' not found in the DataFrame.")
    return df

# List of datasets to fix
datasets = [JPvideos, KRvideos, MXvideos, RUvideos]

# Apply the function to all DataFrames
datasets = [fix_encoding_dataframe(df) for df in datasets]

print("Mojibake correction completed on all datasets!")

Mojibake correction completed on all datasets!

## 1)Create a single dataframe with the concatenation of all input CSV files, adding a column called `country`

In [3]:
#Creating the new column "Country" for each dataframe
#This is a basic pandas way to make a new column called 'Country'. Each dataset has its own Country column with its specific Contry name 
DEvideos['Country'] = "DE"
CAvideos['Country'] = "CA"  
FRvideos['Country'] = "FR"
GBvideos['Country'] = "GB"
INvideos['Country'] = "IN"
USvideos['Country'] = "US"
JPvideos['Country'] = "JP"
KRvideos['Country'] = "KR"
MXvideos['Country'] = "MX"
RUvideos['Country'] = "RU"

#we used the 'pd.concat(a list of pandas objects)' function to concatenate the 10 datasets.  --> a list of pandas objects = such as list of dataframes [data1, data2] 
#Concatenation is a function where every dataset is one on top of the other
concatdataframe = pd.concat([CAvideos,DEvideos,FRvideos,GBvideos,INvideos,USvideos,JPvideos,KRvideos,MXvideos,RUvideos], ignore_index = True)
#with ignore_index = False pd.concat keeps the original indices of the original dataframes
#ignore_index = True will reset the old indexes and it will add a new index for the new dataframe --> concatdataframe

#we want to see only the head of the dataframe
concatdataframe.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA

## 2)Extract all videos that have no tag

In [4]:
# we have noticed that the 'tags' column does not have NA or NaN values (.isna() and .isnull() functions do not work)
# We have only found the string [none] in the tags column
# We assume [none] means no tag
# We have used the string [none] to extract all videos that have no tag
concatdataframe[concatdataframe['tags'] == '[none]']

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Country
41,JwboxqDylgg,17.14.11,Canada Soccer's Women's National Team v USA In...,Canada Soccer,17,2017-11-13T05:53:49.000Z,[none],36311,277,28,13,https://i.ytimg.com/vi/JwboxqDylgg/default.jpg,False,False,False,Canada Soccer's Women's National Team face riv...,CA
58,9B-q8h31Bpk,17.14.11,John Oliver Tackles Louis C.K. And Donald Trum...,TV Shows,22,2017-11-13T04:49:26.000Z,[none],106029,1270,101,181,https://i.ytimg.com/vi/9B-q8h31Bpk/default.jpg,False,False,False,"John Oliver on News, Politics ...",CA
78,1UE5Dq1rvUA,17.14.11,Taylor Swift Perform Ready For It - SNL,Ken Reactz,24,2017-11-12T05:18:02.000Z,[none],320964,8069,285,717,https://i.ytimg.com/vi/1UE5Dq1rvUA/default.jpg,False,False,False,Thanks for watching please subscribe and subsc...,CA
86,pmJQ4KwliX4,17.14.11,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",James Munder,2,2017-11-12T21:25:40.000Z,[none],116820,1503,139,1066,https://i.ytimg.com/vi/pmJQ4KwliX4/default.jpg,False,False,False,https://pastebin.ca/3930472\n\nSupport My Chan...,CA
98,lHcXhBojpeQ,17.14.11,三屆TVB視帝，拋棄10年青梅竹馬髮妻，為娶小三還不惜與母絕交！,明星百曉生,22,2017-11-12T12:49:50.000Z,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375874,TSF_kOdfSkI,18.14.06,Блеск и нищета мнений.,iKakProsto2,24,2018-06-13T16:56:48.000Z,[none],75463,8683,706,1483,https://i.ytimg.com/vi/TSF_kOdfSkI/default.jpg,False,False,False,Небольшой подкаст в котором я хочу поговорить ...,RU
375888,WtRWjVzmPGU,18.14.06,Чем Трамп напугал Киев,Pronorus News,25,2018-06-13T07:37:09.000Z,[none],84234,502,66,91,https://i.ytimg.com/vi/WtRWjVzmPGU/default.jpg,False,False,False,🔴 Наш канал на Яндекс Дзене https://zen.yandex...,RU
375909,kzxD8E-Qebk,18.14.06,Gevorg Martirosyan & Spitakci Hayko - Bola Bol...,DJ NAREK Official,10,2018-06-13T02:32:33.000Z,[none],101059,3152,88,0,https://i.ytimg.com/vi/kzxD8E-Qebk/default.jpg,True,False,False,instagram-https://www.instagram.com/zaqoyannar...,RU
375919,KSG9HCJGfHE,18.14.06,Хатидже дала пощечину Хюррем | Хатидже передум...,Globuzz TV Великолепный Век,22,2018-06-12T12:58:04.000Z,[none],45543,532,81,159,https://i.ytimg.com/vi/KSG9HCJGfHE/default.jpg,False,False,False,3 сезон 65 серия,RU
375939,KAyj5Xm1C64,18.14.06,[ENG SUB] BTS PROM PARTY 2018 Intro + 2nd Gran...,DaisyxBTS 07,24,2018-06-13T12:51:23.000Z,[none],449611,24808,93,974,https://i.ytimg.com/vi/KAyj5Xm1C64/default.jpg,False,False,False,***I do NOT own anything. Just want to share t...,RU

## 3)For each channel, determine the total number of views

In [5]:
# we applied --> dataframe.groupby(by label) and [[column]].sum()
# by default dataframe.groupby sets as_index = True 
concatdataframe.groupby('channel_title')[['views']].sum() #we put double square brackets in order to get back a dataframe
#we summed all the views which are linked to that specific channel

                          views
channel_title
! 세상에 무슨일이              3942977
!!8時だよ面白ネタ大集合             50207
!BTS・TWICE まとめ             7310
!Los amorosos Virales¡     6069
!t Live                  240038
...                         ...
５分でできる DIY               272607
ＢＡＳＨｔｖ                   116292
Ｋのフィッシングちゃんねる             37165
ＷＡＪＯＩＫＡ                  424129
💜Sandrea                 347155

[37824 rows x 1 columns]

## 4)Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe

In [6]:
# we have applied the following condition: ((condition1) and (condition2)) or (condition3) 
# and --> &
# or --> |
excluded = concatdataframe[((concatdataframe['comments_disabled'] == True) & (concatdataframe['ratings_disabled'] == True))|(concatdataframe['video_error_or_removed'] == True)]
# excluded is the newdataframe 
excluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Country
173,H8IWLEtFt9A,17.14.11,Intégrale - On n'est pas couché 11 novembre 20...,On n'est pas couché,24,2017-11-12T01:44:07.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",122282,0,0,0,https://i.ytimg.com/vi/H8IWLEtFt9A/default.jpg,True,True,False,Intégrale - On n'est pas couché 11 novembre 20...,CA
1069,om-_yJaSW_Y,17.19.11,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",523258,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
1278,om-_yJaSW_Y,17.20.11,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",1004809,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
1320,faJOpxEyTWk,17.20.11,Intégrale - On n'est pas couché 18 novembre 20...,On n'est pas couché,24,2017-11-19T02:01:15.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",87544,0,0,0,https://i.ytimg.com/vi/faJOpxEyTWk/default.jpg,True,True,False,Intégrale - On n'est pas couché 18 novembre 20...,CA
1573,om-_yJaSW_Y,17.21.11,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",1197269,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371078,P8H1Ax9j0ts,18.20.05,Արտակարգ դեպք Երևանում. քաղաքացին անցել է կամր...,Gagik SHAMSHYAN,25,2018-05-18T11:55:18.000Z,"Տեսանյութը` Գագիկ Շամշյանի|""video by Gagik Sha...",97934,0,0,0,https://i.ytimg.com/vi/P8H1Ax9j0ts/default.jpg,True,True,False,Այս պահին մի տղամարդ անցել է Հաղթանակ կամրջի վ...,RU
371091,e7nLJVEHtZE,18.21.05,БУ ҚИЗ СЕВИНЧ БИЛАН РАҚСДА УНИ ОРТДА ҚОЛДИРДИ!,Sayyod. Com,10,2018-05-20T12:00:35.000Z,"ўзбек|""intervyu""|""интервью""|""ўзбекча""|""клип""|""...",286460,0,0,0,https://i.ytimg.com/vi/e7nLJVEHtZE/default.jpg,True,True,False,СЕВИНЧ билан ЛИКИР-ШОУ! Севинч билан Севинчдек...,RU
371348,e7nLJVEHtZE,18.22.05,БУ ҚИЗ СЕВИНЧ БИЛАН РАҚСДА УНИ ОРТДА ҚОЛДИРДИ!,Sayyod. Com,10,2018-05-20T12:00:35.000Z,"ўзбек|""intervyu""|""интервью""|""ўзбекча""|""клип""|""...",666118,0,0,0,https://i.ytimg.com/vi/e7nLJVEHtZE/default.jpg,True,True,False,СЕВИНЧ билан ЛИКИР-ШОУ! Севинч билан Севинчдек...,RU
372714,uNq8pmtrCHw,18.29.05,Русские Боевики ПОБЕГ ИЗ КОЛОНИИ Детективы Кри...,ВОЕННОЕ КИНО ВОЕННЫЕ ФИЛЬМЫ !,1,2018-05-28T09:00:08.000Z,"Военные Фильмы|""Военное Кино""|""Боевик""|""Кино""|...",191311,0,0,0,https://i.ytimg.com/vi/uNq8pmtrCHw/default.jpg,True,True,False,Осужденный Фёдор Строгов Военные Фильмы решает...,RU
374662,O31TqiO-NmE,18.08.06,Мастер-класс Выйти на новый уровень,БМ LIFE,27,2018-06-07T20:21:57.000Z,"бизнес молодость|""бм""|""бизнес""|""пётр осипов""",19146,0,0,0,https://i.ytimg.com/vi/O31TqiO-NmE/default.jpg,True,True,False,Выйдите на новый уровень! Прокачайте свой бизн...,RU

In [7]:
# now we remove the 'excluded' rows from the original dataframe
# 'excluded' dataframe has the original indexes of the original dataframe. 
# We exploited the original indexes in the excluded dataframe to drop these rows from the original dataframe
# we used 'dataframe.drop' function. 
# As argument we used index which requires a single label or a list like --> list like = exluded.index in our case
concatdataframe_excluded = concatdataframe.drop(index = excluded.index) #by default axis = 0 
#it will drop only the rows that have the same indexes that are in the excluded dataframe
concatdataframe_excluded
#we should reset index in order to have a new index for concatdataframe_excluded. Indeed the number of rows 373322 is not equal to the last index 375941

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,OMmR9THjVKM,18.14.06,У меня СДВГ! (Story booth на русском) Русская ...,Pastime Time,22,2018-06-13T13:47:01.000Z,"story booth на русском|""story booth перевод""|""...",129488,5893,164,990,https://i.ytimg.com/vi/OMmR9THjVKM/default.jpg,False,False,False,Котики в Blade and Soul - https://bit.ly/2JoOq...,RU
375938,tX7p7NtNVDE,18.14.06,Мои Детские Травмы 2 (анимация),CaGArt,23,2018-06-12T09:38:38.000Z,"кагарт|""каги""|""цагарт""|""гагарт""|""какарт""|""милш...",99163,4659,337,692,https://i.ytimg.com/vi/tX7p7NtNVDE/default.jpg,False,False,False,Мои Детские Травмы 2 (анимация) ▶️Ск...,RU
375939,KAyj5Xm1C64,18.14.06,[ENG SUB] BTS PROM PARTY 2018 Intro + 2nd Gran...,DaisyxBTS 07,24,2018-06-13T12:51:23.000Z,[none],449611,24808,93,974,https://i.ytimg.com/vi/KAyj5Xm1C64/default.jpg,False,False,False,***I do NOT own anything. Just want to share t...,RU
375940,4PiSLIrsSiY,18.14.06,ОБЗОР ВАННОЙ КОМНАТЫ🛁/ТУАЛЕТНОЙ КОМНАТЫ🚽 + ДЕК...,Ксюша Лебедева,22,2018-06-13T00:23:33.000Z,"рум тур ванной комнаты|""room tour bathroom""|""д...",14225,793,39,209,https://i.ytimg.com/vi/4PiSLIrsSiY/default.jpg,False,False,False,"Обзор ванной комнаты, туалетной комнаты+ декор...",RU
375941,Ehy5foVfKOE,18.14.06,Плохой сигнал. Стань человеком!,Tubus Show,29,2018-06-13T09:50:09.000Z,"плохой сигнал|""тубус шоу""|""reebok""|""стань чело...",52340,7708,133,1819,https://i.ytimg.com/vi/Ehy5foVfKOE/default.jpg,False,False,False,В 90-х годах прошлого века произошло коренное ...,RU

## 5)Add a like_ratio column storing the ratio between the number of likes and of dislikes

In [8]:
#firstly we made a function in order to do the ratio only if dislikes takes a value > 0. 
#If dislikes is equal to zero the function returns NA
#pd.NA is a pandas way to represent missing values, we cannot write only NA beacuse it does not exist in python
def ratio(row):
    if row['dislikes'] != 0:
        return row['likes']/row['dislikes']
    return pd.NA

#we add like_ratio column to concatdataframe dataframe
#arguments
# ratio = name of our function
# axis = 1 --> we want to apply our function to each row in order to to the ratio for each row
concatdataframe['like_ratio'] = concatdataframe.apply(ratio, axis = 1)
concatdataframe

# concatdataframe['like_ratio'] = concatdataframe['likes'] / concatdataframe['dislikes']
# Of course there is another way to solve this but we wanted to apply a function in order to
# solve the problem of dislikes = 0

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Country,like_ratio
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.3525
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,OMmR9THjVKM,18.14.06,У меня СДВГ! (Story booth на русском) Русская ...,Pastime Time,22,2018-06-13T13:47:01.000Z,"story booth на русском|""story booth перевод""|""...",129488,5893,164,990,https://i.ytimg.com/vi/OMmR9THjVKM/default.jpg,False,False,False,Котики в Blade and Soul - https://bit.ly/2JoOq...,RU,35.932927
375938,tX7p7NtNVDE,18.14.06,Мои Детские Травмы 2 (анимация),CaGArt,23,2018-06-12T09:38:38.000Z,"кагарт|""каги""|""цагарт""|""гагарт""|""какарт""|""милш...",99163,4659,337,692,https://i.ytimg.com/vi/tX7p7NtNVDE/default.jpg,False,False,False,Мои Детские Травмы 2 (анимация) ▶️Ск...,RU,13.824926
375939,KAyj5Xm1C64,18.14.06,[ENG SUB] BTS PROM PARTY 2018 Intro + 2nd Gran...,DaisyxBTS 07,24,2018-06-13T12:51:23.000Z,[none],449611,24808,93,974,https://i.ytimg.com/vi/KAyj5Xm1C64/default.jpg,False,False,False,***I do NOT own anything. Just want to share t...,RU,266.752688
375940,4PiSLIrsSiY,18.14.06,ОБЗОР ВАННОЙ КОМНАТЫ🛁/ТУАЛЕТНОЙ КОМНАТЫ🚽 + ДЕК...,Ксюша Лебедева,22,2018-06-13T00:23:33.000Z,"рум тур ванной комнаты|""room tour bathroom""|""д...",14225,793,39,209,https://i.ytimg.com/vi/4PiSLIrsSiY/default.jpg,False,False,False,"Обзор ванной комнаты, туалетной комнаты+ декор...",RU,20.333333
375941,Ehy5foVfKOE,18.14.06,Плохой сигнал. Стань человеком!,Tubus Show,29,2018-06-13T09:50:09.000Z,"плохой сигнал|""тубус шоу""|""reebok""|""стань чело...",52340,7708,133,1819,https://i.ytimg.com/vi/Ehy5foVfKOE/default.jpg,False,False,False,В 90-х годах прошлого века произошло коренное ...,RU,57.954887

In [9]:
concatdataframe[concatdataframe['like_ratio'].isna()][['like_ratio']] #all the rows with Na in like ratio column

       like_ratio
67           <NA>
161          <NA>
173          <NA>
235          <NA>
271          <NA>
...           ...
375556       <NA>
375664       <NA>
375719       <NA>
375861       <NA>
375871       <NA>

[9763 rows x 1 columns]

## 6)Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [10]:
concatdataframe['publish_time']  #dtype = object

0         2017-11-10T17:00:03.000Z
1         2017-11-13T17:00:00.000Z
2         2017-11-12T19:05:24.000Z
3         2017-11-12T18:01:41.000Z
4         2017-11-09T11:04:14.000Z
                    ...
375937    2018-06-13T13:47:01.000Z
375938    2018-06-12T09:38:38.000Z
375939    2018-06-13T12:51:23.000Z
375940    2018-06-13T00:23:33.000Z
375941    2018-06-13T09:50:09.000Z
Name: publish_time, Length: 375942, dtype: object

In [11]:
import datetime #python library
#concatdataframe['publish_time'] series dtype object --> this is why we convert it in a time to be readable by pandas
concatdataframe['publish_time'] = pd.to_datetime(concatdataframe['publish_time'], format='mixed')
#to_datetime help us to transform object in datetimes in order to apply datetime functions
# format='mixed' means that the datetime values may have different formats
#exploiting "format = 'mixed' " argument we can transform every different format to a unique format

# dt.floor --> to round datetime object down to a specified frequency --> dt.floor(frequency)
# if we want to round to hour, let's suppose 12:20:03 we will get 12:00:00
# in our case we wanted to round to minutes to the nearest multiple of 10
concatdataframe['interval_start'] = concatdataframe['publish_time'].dt.floor('10min')  #pandas function which requires a series
# timedelta is very usefull to do operations with time, in our case we have exploited timedelta to ad 10 minutes to the initial interval
concatdataframe['interval_end'] = concatdataframe['interval_start'] + datetime.timedelta(minutes=10)  
concatdataframe

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Country,like_ratio,interval_start,interval_end
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,2017-11-10 17:00:00+00:00,2017-11-10 17:10:00+00:00
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346,2017-11-13 17:00:00+00:00,2017-11-13 17:10:00+00:00
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.3525,2017-11-12 19:00:00+00:00,2017-11-12 19:10:00+00:00
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168,2017-11-12 18:00:00+00:00,2017-11-12 18:10:00+00:00
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044,2017-11-09 11:00:00+00:00,2017-11-09 11:10:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,OMmR9THjVKM,18.14.06,У меня СДВГ! (Story booth на русском) Русская ...,Pastime Time,22,2018-06-13 13:47:01+00:00,"story booth на русском|""story booth перевод""|""...",129488,5893,164,990,https://i.ytimg.com/vi/OMmR9THjVKM/default.jpg,False,False,False,Котики в Blade and Soul - https://bit.ly/2JoOq...,RU,35.932927,2018-06-13 13:40:00+00:00,2018-06-13 13:50:00+00:00
375938,tX7p7NtNVDE,18.14.06,Мои Детские Травмы 2 (анимация),CaGArt,23,2018-06-12 09:38:38+00:00,"кагарт|""каги""|""цагарт""|""гагарт""|""какарт""|""милш...",99163,4659,337,692,https://i.ytimg.com/vi/tX7p7NtNVDE/default.jpg,False,False,False,Мои Детские Травмы 2 (анимация) ▶️Ск...,RU,13.824926,2018-06-12 09:30:00+00:00,2018-06-12 09:40:00+00:00
375939,KAyj5Xm1C64,18.14.06,[ENG SUB] BTS PROM PARTY 2018 Intro + 2nd Gran...,DaisyxBTS 07,24,2018-06-13 12:51:23+00:00,[none],449611,24808,93,974,https://i.ytimg.com/vi/KAyj5Xm1C64/default.jpg,False,False,False,***I do NOT own anything. Just want to share t...,RU,266.752688,2018-06-13 12:50:00+00:00,2018-06-13 13:00:00+00:00
375940,4PiSLIrsSiY,18.14.06,ОБЗОР ВАННОЙ КОМНАТЫ🛁/ТУАЛЕТНОЙ КОМНАТЫ🚽 + ДЕК...,Ксюша Лебедева,22,2018-06-13 00:23:33+00:00,"рум тур ванной комнаты|""room tour bathroom""|""д...",14225,793,39,209,https://i.ytimg.com/vi/4PiSLIrsSiY/default.jpg,False,False,False,"Обзор ванной комнаты, туалетной комнаты+ декор...",RU,20.333333,2018-06-13 00:20:00+00:00,2018-06-13 00:30:00+00:00
375941,Ehy5foVfKOE,18.14.06,Плохой сигнал. Стань человеком!,Tubus Show,29,2018-06-13 09:50:09+00:00,"плохой сигнал|""тубус шоу""|""reebok""|""стань чело...",52340,7708,133,1819,https://i.ytimg.com/vi/Ehy5foVfKOE/default.jpg,False,False,False,В 90-х годах прошлого века произошло коренное ...,RU,57.954887,2018-06-13 09:50:00+00:00,2018-06-13 10:00:00+00:00

## 7)For each interval, determine the number of videos, average number of likes and of dislikes.

In [12]:
#to solve this we applied groupby and merge functions
df1 = concatdataframe.groupby(['interval_start','interval_end'], as_index = False)['video_id'].count()[['interval_start','interval_end','video_id']]
df2 = concatdataframe.groupby(['interval_start','interval_end'],as_index = False)['likes'].mean()[['interval_start','interval_end','likes']]
df3 = concatdataframe.groupby(['interval_start','interval_end'],as_index = False)['dislikes'].mean()[['interval_start','interval_end','dislikes']]
df1

                 interval_start              interval_end  video_id
0     2006-07-23 08:20:00+00:00 2006-07-23 08:30:00+00:00         1
1     2007-03-05 16:20:00+00:00 2007-03-05 16:30:00+00:00         9
2     2007-06-25 06:50:00+00:00 2007-06-25 07:00:00+00:00        12
3     2007-12-03 20:50:00+00:00 2007-12-03 21:00:00+00:00        16
4     2008-01-07 21:20:00+00:00 2008-01-07 21:30:00+00:00        10
...                         ...                       ...       ...
30418 2018-06-14 02:30:00+00:00 2018-06-14 02:40:00+00:00         1
30419 2018-06-14 03:00:00+00:00 2018-06-14 03:10:00+00:00         2
30420 2018-06-14 03:20:00+00:00 2018-06-14 03:30:00+00:00         1
30421 2018-06-14 03:30:00+00:00 2018-06-14 03:40:00+00:00         1
30422 2018-06-14 03:40:00+00:00 2018-06-14 03:50:00+00:00         1

[30423 rows x 3 columns]

In [13]:
#we applied the pandas merge function --> df1.merge(df2, how = 'inner', on = label or list)  
#how = 'inner' this argument thath allow us to do a sql join in pandas
#by the argument 'on = label or list' we specify the columns used for the join, in our case we take interval start and end 
df1df2 = df1.merge(df2, how = 'inner', on = ['interval_start','interval_end'])
df1df2

,interval_start,interval_end,video_id,likes
0,2006-07-23 08:20:00+00:00,2006-07-23 08:30:00+00:00,1,459.000000
1,2007-03-05 16:20:00+00:00,2007-03-05 16:30:00+00:00,9,336.666667
2,2007-06-25 06:50:00+00:00,2007-06-25 07:00:00+00:00,12,579.833333
3,2007-12-03 20:50:00+00:00,2007-12-03 21:00:00+00:00,16,187.937500
4,2008-01-07 21:20:00+00:00,2008-01-07 21:30:00+00:00,10,99.900000
...,...,...,...,...
30418,2018-06-14 02:30:00+00:00,2018-06-14 02:40:00+00:00,1,853.000000
30419,2018-06-14 03:00:00+00:00,2018-06-14 03:10:00+00:00,2,2304.500000
30420,2018-06-14 03:20:00+00:00,2018-06-14 03:30:00+00:00,1,1414.000000
30421,2018-06-14 03:30:00+00:00,2018-06-14 03:40:00+00:00,1,8481.000000
30422,2018-06-14 03:40:00+00:00,2018-06-14 03:50:00+00:00,1,374.000000

In [14]:
df1df2df3 = df1df2.merge(df3, how = 'inner', on = ['interval_start','interval_end'] )
df1df2df3

,interval_start,interval_end,video_id,likes,dislikes
0,2006-07-23 08:20:00+00:00,2006-07-23 08:30:00+00:00,1,459.000000,152.0000
1,2007-03-05 16:20:00+00:00,2007-03-05 16:30:00+00:00,9,336.666667,2.0000
2,2007-06-25 06:50:00+00:00,2007-06-25 07:00:00+00:00,12,579.833333,11.5000
3,2007-12-03 20:50:00+00:00,2007-12-03 21:00:00+00:00,16,187.937500,15.6875
4,2008-01-07 21:20:00+00:00,2008-01-07 21:30:00+00:00,10,99.900000,2.0000
...,...,...,...,...,...
30418,2018-06-14 02:30:00+00:00,2018-06-14 02:40:00+00:00,1,853.000000,77.0000
30419,2018-06-14 03:00:00+00:00,2018-06-14 03:10:00+00:00,2,2304.500000,31.5000
30420,2018-06-14 03:20:00+00:00,2018-06-14 03:30:00+00:00,1,1414.000000,28.0000
30421,2018-06-14 03:30:00+00:00,2018-06-14 03:40:00+00:00,1,8481.000000,252.0000
30422,2018-06-14 03:40:00+00:00,2018-06-14 03:50:00+00:00,1,374.000000,24.0000

## 8)For each tag, determine the number of videos
#### Notice that tags contains a string with several tags

In [15]:
#we create a copy to do our analysis because we have to modify the dataframe. Copy in order to dont modify the original dataframe
video_idtags = concatdataframe[['video_id','tags','Country','like_ratio']].copy()
video_idtags

,video_id,tags,Country,like_ratio
0,n1WpP7iowLc,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",CA,18.135076
1,0dBIkQ4Mz1M,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",CA,75.707346
2,5qpjK5DgCt4,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",CA,27.3525
3,d380meD0W0M,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",CA,66.485168
4,2Vv-BfVoq4g,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",CA,77.513044
...,...,...,...,...
375937,OMmR9THjVKM,"story booth на русском|""story booth перевод""|""...",RU,35.932927
375938,tX7p7NtNVDE,"кагарт|""каги""|""цагарт""|""гагарт""|""какарт""|""милш...",RU,13.824926
375939,KAyj5Xm1C64,[none],RU,266.752688
375940,4PiSLIrsSiY,"рум тур ванной комнаты|""room tour bathroom""|""д...",RU,20.333333
375941,Ehy5foVfKOE,"плохой сигнал|""тубус шоу""|""reebok""|""стань чело...",RU,57.954887

In [16]:
#as we can see tags contains a string with several tags
#we have to separate every tag
#we start removing " and | by making a python function
def splitter_list(row):
    if row['tags'] != '[none]':
        return [t.strip() for t in row['tags'].replace('"','').split('|')]  #split separates the tags and create a list
    return ['[none]'] 

#we put none in a list in order to after apply the explode function 

video_idtags['tags'] = video_idtags.apply(splitter_list, axis = 1)

In [17]:
#We applied strip() because blank spaces could cause errors when using the groupby function

In [18]:
video_idtags

,video_id,tags,Country,like_ratio
0,n1WpP7iowLc,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",CA,18.135076
1,0dBIkQ4Mz1M,"[plush, bad unboxing, unboxing, fan mail, idub...",CA,75.707346
2,5qpjK5DgCt4,"[racist superman, rudy, mancuso, king, bach, r...",CA,27.3525
3,d380meD0W0M,"[ryan, higa, higatv, nigahiga, i dare you, idy...",CA,66.485168
4,2Vv-BfVoq4g,"[edsheeran, ed sheeran, acoustic, live, cover,...",CA,77.513044
...,...,...,...,...
375937,OMmR9THjVKM,"[story booth на русском, story booth перевод, ...",RU,35.932927
375938,tX7p7NtNVDE,"[кагарт, каги, цагарт, гагарт, какарт, милшу, ...",RU,13.824926
375939,KAyj5Xm1C64,[[none]],RU,266.752688
375940,4PiSLIrsSiY,"[рум тур ванной комнаты, room tour bathroom, д...",RU,20.333333
375941,Ehy5foVfKOE,"[плохой сигнал, тубус шоу, reebok, стань челов...",RU,57.954887

In [19]:
video_idtags_exploded = video_idtags.explode('tags', ignore_index=True) #ignore_index = True to reset the index
# DataFrame.drop(labels= list like, axis=0) axis = 0 by default. 0 refers to indexes. 1 refers to columns
video_idtags_exploded.groupby('tags')[['video_id']].count().drop(labels= ['','[none]'])  #we will copy and paste this line of code to solve the 9th question

                                                 video_id
tags
! Banii i-au luat mintile                               2
!!                                                      5
!! *me bloquea*                                         1
!!!                                                     1
!!!!                                                    2
...                                                   ...
😥                                                       2
😭 #résistancelamaindesqueezie ❤️                        1
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية         1
🚀 smartpixel.com.ua                                     1
🤝 ZARBEX zahlt Schutzgeld!!!                            1

[852595 rows x 1 columns]

In [20]:
video_idtags_exploded.groupby('tags')[['video_id']].count() #dataframe without dropping

                                                 video_id
tags
                                                      732
! Banii i-au luat mintile                               2
!!                                                      5
!! *me bloquea*                                         1
!!!                                                     1
...                                                   ...
😥                                                       2
😭 #résistancelamaindesqueezie ❤️                        1
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية         1
🚀 smartpixel.com.ua                                     1
🤝 ZARBEX zahlt Schutzgeld!!!                            1

[852597 rows x 1 columns]

## 9)Find the tags with the largest number of videos

In [21]:
video_idtags_exploded.groupby('tags')[['video_id']].count().drop(labels= ['','[none]']).sort_values("video_id", axis = 0, ascending=False) 
#sort in ascending false way and sort using as reference video_id, sort every by row 
#the tags with the largest number of videos will apear on the head of the dataframe

                                                    video_id
tags
funny                                                  15075
comedy                                                 12356
2018                                                   11402
news                                                    6415
music                                                   5918
...                                                      ...
#044                                                       1
#1 Pick                                                    1
#1015                                                      1
#1015 Luffy sets sail to a new Island - Foxy's ...         1
#1027                                                      1

[852595 rows x 1 columns]

## 10)For each (tag, country) pair, compute average ratio likes/dislikes

In [22]:
video_idtags_exploded

            video_id                        tags Country like_ratio
0        n1WpP7iowLc                      Eminem      CA  18.135076
1        n1WpP7iowLc                        Walk      CA  18.135076
2        n1WpP7iowLc                          On      CA  18.135076
3        n1WpP7iowLc                       Water      CA  18.135076
4        n1WpP7iowLc  Aftermath/Shady/Interscope      CA  18.135076
...              ...                         ...     ...        ...
6487332  Ehy5foVfKOE                     фитнесс      RU  57.954887
6487333  Ehy5foVfKOE                    кроссфит      RU  57.954887
6487334  Ehy5foVfKOE        здоровый образ жизни      RU  57.954887
6487335  Ehy5foVfKOE                   фитоняшки      RU  57.954887
6487336  Ehy5foVfKOE                  инстаграмм      RU  57.954887

[6487337 rows x 4 columns]

In [23]:
#we used the previous dataframe video_idtags_exploded
#then we removed the unnecessary tags
#at the end we did a group by and we computed for each(tag, country) pair the average ratio likes/dislikes
drop = video_idtags_exploded[(video_idtags_exploded['tags'] == '')|(video_idtags_exploded['tags'] == '[none]')].index #by writing index this function returns 
# a list like of indexes that matches the condition
drop

Index([    888,    1187,    1536,    1737,    1999,    2000,    2292,    2354,
          2374,    2491,
       ...
       6484650, 6484711, 6485129, 6485265, 6485929, 6485970, 6486261, 6486676,
       6486853, 6487314],
      dtype='int64', length=38430)

In [24]:
video_idtags_exploded.drop(labels = drop, axis = 0).groupby(['tags','Country'])[['like_ratio']].mean()  #labels = list like 
#pandas ignora automaticamente i valori pd.NA o NaN quando calcola la media
#as chatgpt says 'tags' country could have that blank space due to a encoding error --> in it's opinion it is a special character because we have already 
#removed every blank space with drop and strip functions

                                                        like_ratio
tags                                            Country
! Banii i-au luat mintile                       DE        6.222739
!!                                              FR       12.452875
                                                MX       38.081559
!! *me bloquea*                                 MX        65.26087
!!!                                             MX       12.952381
...                                                            ...
😥                                               DE       26.384615
😭 #résistancelamaindesqueezie ❤️                FR       10.219048
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية FR        6.223873
🚀 smartpixel.com.ua                             RU        0.714286
🤝 ZARBEX zahlt Schutzgeld!!!                    DE       13.989691

[1102627 rows x 1 columns]

In [25]:
#this does not affect the results since all identical improperly decoded tags will be grouped together

## 11)For each (trending_date, country) pair, the video with the largest number of views

In [26]:
idx = concatdataframe.groupby(['trending_date','Country'],as_index = False)['views'].idxmax()
idx['views']
#3398 is the index of the row that has trending_date country pair with the largest number of views of that specific pair

0         3398
1        44280
2        85252
3       126032
4       164617
         ...
1962    257741
1963    292147
1964    332432
1965    373007
1966    236859
Name: views, Length: 1967, dtype: int64

In [27]:
#loc requires as argument a series of indexes
#loc return the entire row
concatdataframe.loc[idx['views']].reset_index(drop=True)[['trending_date','Country','video_id','views']]
#drop = True in order to do not transform the old index into a column

     trending_date Country     video_id      views
0         17.01.12      CA  6ZfuNTqbHE8   56367282
1         17.01.12      DE  6ZfuNTqbHE8   56367282
2         17.01.12      FR  3VbHg5fqBYw    7281189
3         17.01.12      GB  TyHvyGVs42U  143408235
4         17.01.12      IN  6ZfuNTqbHE8   56367282
...            ...     ...          ...        ...
1962      18.31.05      JP  aJOTlE1K90k    3057987
1963      18.31.05      KR  ntWSnDV0MYs    4150448
1964      18.31.05      MX  xTlNMmZKwpA   20723565
1965      18.31.05      RU  1nX0kF2UwDc    3125598
1966      18.31.05      US  VYOjWnS4cMY  217750076

[1967 rows x 4 columns]

In [28]:
concatdataframe.loc[idx['views']][['trending_date','Country','video_id','views']]

       trending_date Country     video_id      views
3398        17.01.12      CA  6ZfuNTqbHE8   56367282
44280       17.01.12      DE  6ZfuNTqbHE8   56367282
85252       17.01.12      FR  3VbHg5fqBYw    7281189
126032      17.01.12      GB  TyHvyGVs42U  143408235
164617      17.01.12      IN  6ZfuNTqbHE8   56367282
...              ...     ...          ...        ...
257741      18.31.05      JP  aJOTlE1K90k    3057987
292147      18.31.05      KR  ntWSnDV0MYs    4150448
332432      18.31.05      MX  xTlNMmZKwpA   20723565
373007      18.31.05      RU  1nX0kF2UwDc    3125598
236859      18.31.05      US  VYOjWnS4cMY  217750076

[1967 rows x 4 columns]

## 12)Divide trending_date into three columns: year, month, day

In [29]:
# we wont use the datetime library to solve this exercise. We will use the dt.date pandas's integrated function to solve it
concatdataframe_date = concatdataframe[['trending_date']].copy()
concatdataframe_date #dtype object --> necessary transform it into datetime type

       trending_date
0           17.14.11
1           17.14.11
2           17.14.11
3           17.14.11
4           17.14.11
...              ...
375937      18.14.06
375938      18.14.06
375939      18.14.06
375940      18.14.06
375941      18.14.06

[375942 rows x 1 columns]

In [30]:
concatdataframe_date['trending_date'] = pd.to_datetime(concatdataframe_date['trending_date'], format="%y.%d.%m") #change to datetime format
concatdataframe_date['year'] = concatdataframe_date['trending_date'].dt.year  #series.dt.year  --> it returns the year. I'm creating a new column 'year'
concatdataframe_date['month'] = concatdataframe_date['trending_date'].dt.month
concatdataframe_date['day'] = concatdataframe_date['trending_date'].dt.day
concatdataframe_date

       trending_date  year  month  day
0         2017-11-14  2017     11   14
1         2017-11-14  2017     11   14
2         2017-11-14  2017     11   14
3         2017-11-14  2017     11   14
4         2017-11-14  2017     11   14
...              ...   ...    ...  ...
375937    2018-06-14  2018      6   14
375938    2018-06-14  2018      6   14
375939    2018-06-14  2018      6   14
375940    2018-06-14  2018      6   14
375941    2018-06-14  2018      6   14

[375942 rows x 4 columns]

## 13)For each (month, country) pair, the video with the largest number of views

In [31]:
concatdataframe['trending_date'] = pd.to_datetime(concatdataframe['trending_date'], format="%y.%d.%m")
concatdataframe['month'] = concatdataframe['trending_date'].dt.month

index = concatdataframe.groupby(['month','Country'], as_index = False)['views'].idxmax()
concatdataframe.loc[index['views']][['month','Country','views']]

        month Country      views
11214       1      CA   43067983
51930       1      DE   37728802
92853       1      FR   37728802
135208      1      GB   90598955
173405      1      IN   42019590
...       ...     ...        ...
166769     12      IN  125432237
265041     12      KR  113876217
300013     12      MX  100912384
340036     12      RU   52611730
204894     12      US  149376127

[77 rows x 3 columns]

## 14)Read all json files with the video categories

In [32]:
import json

file_names = [r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_json_files\CA_category_id.json",
              r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_json_files\DE_category_id.json",
              r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_json_files\FR_category_id.json",
              r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_json_files\GB_category_id.json",
              r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_json_files\IN_category_id.json",
              r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_json_files\JP_category_id.json",
              r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_json_files\KR_category_id.json",
              r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_json_files\MX_category_id.json",
              r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_json_files\RU_category_id.json",
              r"C:\Users\arnol\OneDrive\Desktop\TrendingYT_dataset\trendingYT_json_files\US_category_id.json"]
jsonlist_of_df = []
for f in file_names:
    with open(f,"r", encoding="utf-8") as s:
        data = json.load(s)
        jsonlist_of_df.append(data)
jsonlist_of_df[0] #they are not readable yet, they are in json format

{'kind': 'youtube#videoCategoryListResponse',
 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2qTj13hkQZk"',
 'items': [{'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKmPBggty2mZQ"',
   'id': '1',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Film & Animation',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45ZTFR3a3NyTA"',
   'id': '2',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Autos & Vehicles',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxbknKFVe5Lmg"',
   'id': '10',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Music',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-oBJavSGkfDI"',
   'id': '15',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Pets & Animals',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM1XVQ9zbGec"',
   'id': '17',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Sports',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/FJwVpGCVZ1yiJrqZbpqe68Sy_OE"',
   'id': '18',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Short Movies',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/M-3iD9dwK7YJCafRf_DkLN8CouA"',
   'id': '19',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Travel & Events',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/WmA0qYEfjWsAoyJFSw2zinhn2wM"',
   'id': '20',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Gaming',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/EapFaGYG7K0StIXVf8aba249tdM"',
   'id': '21',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Videoblogging',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/xId8RX7vRN8rqkbYZbNIytUQDRo"',
   'id': '22',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'People & Blogs',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/G9LHzQmx44rX2S5yaga_Aqtwz8M"',
   'id': '23',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Comedy',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/UVB9oxX2Bvqa_w_y3vXSLVK5E_s"',
   'id': '24',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Entertainment',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/QiLK0ZIrFoORdk_g2l_XR_ECjDc"',
   'id': '25',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'News & Politics',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/r6Ck6Z0_L0rG37VJQR200SGNA_w"',
   'id': '26',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Howto & Style',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/EoYkczo9I3RCf96RveKTOgOPkUM"',
   'id': '27',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Education',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/w5HjcTD82G_XA3xBctS30zS-JpQ"',
   'id': '28',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Science & Technology',
    'assignable': True}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/lL7uWDr_071CHxifjYG1tJrp4Uo"',
   'id': '30',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Movies',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/WnuVfjO-PyFLO7NTRQIbrGE62nk"',
   'id': '31',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Anime/Animation',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/ctpH2hGA_UZ3volJT_FTlOg9M00"',
   'id': '32',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Action/Adventure',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/L0kR3-g1BAo5UD1PLVbQ7LkkDtQ"',
   'id': '33',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Classics',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/pUZOAC_s9sfiwar639qr_wAB-aI"',
   'id': '34',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Comedy',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/Xb5JLhtyNRN3AQq021Ds-OV50Jk"',
   'id': '35',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Documentary',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/u8WXzF4HIhtEi805__sqjuA4lEk"',
   'id': '36',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Drama',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/D04PP4Gr7wc4IV_O9G66Z4A8KWQ"',
   'id': '37',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Family',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/i5-_AceGXQCEEMWU0V8CcQm_vLQ"',
   'id': '38',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Foreign',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/rtlxd0zOixA9QHdIZB26-St5qgQ"',
   'id': '39',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Horror',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/N1TrDFLRppxZgBowCJfJCvh0Dpg"',
   'id': '40',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Sci-Fi/Fantasy',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/7UMGi6zRySqXopr_rv4sZq6Za2E"',
   'id': '41',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Thriller',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/RScXhi324h8usyIetreAVb-uKeM"',
   'id': '42',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Shorts',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiGVrFsuFsd0A"',
   'id': '43',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Shows',
    'assignable': False}},
  {'kind': 'youtube#videoCategory',
   'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/x5NxSf5fz8hn4loSN4rvhwzD_pY"',
   'id': '44',
   'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
    'title': 'Trailers',
    'assignable': False}}]}

In [33]:
jsonlist_of_df[0]['items'] #it works such as a dictionary

[{'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKmPBggty2mZQ"',
  'id': '1',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Film & Animation',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45ZTFR3a3NyTA"',
  'id': '2',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Autos & Vehicles',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxbknKFVe5Lmg"',
  'id': '10',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Music',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-oBJavSGkfDI"',
  'id': '15',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Pets & Animals',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM1XVQ9zbGec"',
  'id': '17',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Sports',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/FJwVpGCVZ1yiJrqZbpqe68Sy_OE"',
  'id': '18',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Short Movies',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/M-3iD9dwK7YJCafRf_DkLN8CouA"',
  'id': '19',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Travel & Events',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/WmA0qYEfjWsAoyJFSw2zinhn2wM"',
  'id': '20',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Gaming',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/EapFaGYG7K0StIXVf8aba249tdM"',
  'id': '21',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Videoblogging',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/xId8RX7vRN8rqkbYZbNIytUQDRo"',
  'id': '22',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'People & Blogs',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/G9LHzQmx44rX2S5yaga_Aqtwz8M"',
  'id': '23',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Comedy',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/UVB9oxX2Bvqa_w_y3vXSLVK5E_s"',
  'id': '24',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Entertainment',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/QiLK0ZIrFoORdk_g2l_XR_ECjDc"',
  'id': '25',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'News & Politics',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/r6Ck6Z0_L0rG37VJQR200SGNA_w"',
  'id': '26',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Howto & Style',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/EoYkczo9I3RCf96RveKTOgOPkUM"',
  'id': '27',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Education',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/w5HjcTD82G_XA3xBctS30zS-JpQ"',
  'id': '28',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Science & Technology',
   'assignable': True}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/lL7uWDr_071CHxifjYG1tJrp4Uo"',
  'id': '30',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Movies',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/WnuVfjO-PyFLO7NTRQIbrGE62nk"',
  'id': '31',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Anime/Animation',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/ctpH2hGA_UZ3volJT_FTlOg9M00"',
  'id': '32',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Action/Adventure',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/L0kR3-g1BAo5UD1PLVbQ7LkkDtQ"',
  'id': '33',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Classics',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/pUZOAC_s9sfiwar639qr_wAB-aI"',
  'id': '34',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Comedy',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/Xb5JLhtyNRN3AQq021Ds-OV50Jk"',
  'id': '35',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Documentary',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/u8WXzF4HIhtEi805__sqjuA4lEk"',
  'id': '36',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Drama',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/D04PP4Gr7wc4IV_O9G66Z4A8KWQ"',
  'id': '37',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Family',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/i5-_AceGXQCEEMWU0V8CcQm_vLQ"',
  'id': '38',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Foreign',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/rtlxd0zOixA9QHdIZB26-St5qgQ"',
  'id': '39',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Horror',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/N1TrDFLRppxZgBowCJfJCvh0Dpg"',
  'id': '40',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Sci-Fi/Fantasy',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/7UMGi6zRySqXopr_rv4sZq6Za2E"',
  'id': '41',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Thriller',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/RScXhi324h8usyIetreAVb-uKeM"',
  'id': '42',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Shorts',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiGVrFsuFsd0A"',
  'id': '43',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Shows',
   'assignable': False}},
 {'kind': 'youtube#videoCategory',
  'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/x5NxSf5fz8hn4loSN4rvhwzD_pY"',
  'id': '44',
  'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
   'title': 'Trailers',
   'assignable': False}}]

In [34]:
jsonpandasdf = []
for f in jsonlist_of_df:
    keyvalueitems = f['items'] 
    pandasjs = pd.json_normalize(keyvalueitems)
    jsonpandasdf.append(pandasjs)

country_name = ['CA','DE','FR','GB','IN','JP','KR','MX','RU','US']
for f in range(len(jsonpandasdf)):
    jsonpandasdf[f]['Country'] = country_name[f]

concatdataframejson = pd.concat(jsonpandasdf, ignore_index = True)
concatdataframejson

,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable,Country
0,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKm...",1,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True,CA
1,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45Z...",2,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles,True,CA
2,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10,UCBR8-60-B28hp2BmDPdntcQ,Music,True,CA
3,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-o...",15,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True,CA
4,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM...",17,UCBR8-60-B28hp2BmDPdntcQ,Sports,True,CA
...,...,...,...,...,...,...,...
306,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/N1TrDFLRppxZgBowC...",40,UCBR8-60-B28hp2BmDPdntcQ,Sci-Fi/Fantasy,False,US
307,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/7UMGi6zRySqXopr_r...",41,UCBR8-60-B28hp2BmDPdntcQ,Thriller,False,US
308,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/RScXhi324h8usyIet...",42,UCBR8-60-B28hp2BmDPdntcQ,Shorts,False,US
309,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43,UCBR8-60-B28hp2BmDPdntcQ,Shows,False,US
310,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/x5NxSf5fz8hn4loSN...",44,UCBR8-60-B28hp2BmDPdntcQ,Trailers,False,US

## 15)For each country, determine how many videos have a category that is not assignable.

In [35]:
#category_id in concatdataframe is inttype
#id in concatdataframejson is ojbect type

concatdataframejson['id'] = concatdataframejson['id'].astype(int)  #now is int 

#i want to do a merge 
concatdataframejson = concatdataframejson.rename(columns={"id": "category_id"})

In [39]:
finaldf = concatdataframe.merge(concatdataframejson, how = 'left', on = ['category_id', 'Country'])[['video_id','category_id','Country','snippet.assignable']]
finaldf[(finaldf['snippet.assignable']==False)|(finaldf['snippet.assignable'].isna())].groupby('Country',as_index = False)['video_id'].count()[["Country","video_id"]]

  Country  video_id
0      CA       204
1      DE       366
2      FR       226
3      GB       110
4      IN       326
5      JP        18
6      KR       455
7      MX       255
8      RU      1736
9      US        57